# Generated by Django 2.2.1 on 2019-05-04 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_shortname', models.CharField(max_length=20)),
                ('branch_longname', models.CharField(max_length=50)),
                ('branch_addressline1', models.CharField(max_length=30)),
                ('branch_addressline2', models.CharField(max_length=30)),
                ('branch_addressline3', models.CharField(max_length=30)),
                ('branch_addressline4', models.CharField(max_length=30)),
                ('branch_state', models.CharField(max_length=10)),
                ('branch_postalcode', models.CharField(max_length=10)),
                ('branch_country', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_shortname', models.CharField(max_length=20)),
                ('company_longname', models.CharField(max_length=50)),
                ('company_registration', models.CharField(max_length=25)),
                ('company_addressline1', models.CharField(max_length=30)),
                ('company_addressline2', models.CharField(max_length=30)),
                ('company_addressline3', models.CharField(max_length=30)),
                ('company_addressline4', models.CharField(max_length=30)),
                ('company_state', models.CharField(max_length=10)),
                ('company_postalcode', models.CharField(max_length=10)),
                ('company_country', models.CharField(max_length=10)),
                ('company_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 4, 11, 43, 54, 159402))),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=50)),
                ('purchaser_nric', models.CharField(max_length=30)),
                ('purchaser_email', models.CharField(max_length=50)),
                ('purchaser_contact_number', models.CharField(max_length=20)),
                ('purchaser_bod', models.DateField()),
                ('citizen', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=30)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('marital_status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Purchasers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Company')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_shortname', models.CharField(max_length=20)),
                ('phase_longname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('phase_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Project')),
            ],
            options={
                'verbose_name_plural': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='Floortype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floortype', models.CharField(max_length=2)),
                ('floor_shortname', models.CharField(max_length=20)),
                ('floor_size', models.CharField(max_length=50)),
                ('block_prefix', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('block_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Phase')),
                ('block_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Project')),
            ],
            options={
                'verbose_name_plural': 'Floortypes',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_shortname', models.CharField(max_length=20)),
                ('block_longname', models.CharField(max_length=50)),
                ('block_prefix', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('block_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Phase')),
                ('block_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Project')),
            ],
            options={
                'verbose_name_plural': 'Blocks',
            },
        ),
    ]
