# Generated by Django 2.2.1 on 2019-05-06 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 6, 11, 28, 56, 627000)),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_unit', models.CharField(max_length=10)),
                ('property_row', models.DecimalField(decimal_places=2, max_digits=6)),
                ('property_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_bookingstatus', models.CharField(max_length=10)),
                ('property_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Phase')),
                ('property_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Project')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
