# Generated by Django 2.2.1 on 2019-05-30 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20190506_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='No'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 30, 10, 1, 6, 296202)),
        ),
    ]
