# Generated by Django 2.2.1 on 2019-05-30 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190530_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 30, 10, 6, 42, 411702)),
        ),
    ]
