# Generated by Django 2.2.1 on 2019-07-02 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20190530_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_cat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 16, 33, 46, 131168)),
        ),
    ]
