# Generated by Django 2.2.1 on 2019-07-02 08:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20190702_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='modify_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='modify_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 16, 44, 37, 685212)),
        ),
    ]
